# -*- coding: utf-8 -*-
"""LINEAR REGRESSION MODEL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YF-KqES5vwNAzNZTy9Rno0DDykwvXWe
"""

import matplotlib.pyplot as plt

import numpy as np

from sklearn.metrics import mean_squared_error#Mean_squared_error is imported from sklearn library

from sklearn import datasets,linear_model#linear_model is imported from sklearn linrary

diabetes = datasets.load_diabetes()#THE DIABETES DATASET IS LOADED FROM THE DATASETS IMPORTED FROM SKLEARN

print(diabetes.keys())

print(diabetes.DESCR)

diabetes_x=diabetes.data[:,np.newaxis,2]#Here we get the independent variables which is stored in diabetes_x
print(diabetes_x)
#Here diabetes_x comprises of all the values of the axis 2

diabetes_x_train=diabetes_x[:-30]#30 amount of data is taken for training the data
diabetes_x_test=diabetes_x[:-30]#30 amount of data is taken for testing the data
#THIS METHOD IS CALLED TRAIN TEST SLICING
#The data is split into training and testing sets

diabetes_y_train=diabetes.target[:-30] #Here target() refers to the target variable which contains the variables,the regression model
#aims to predict,Here diabetes_y_train is the variable defined which will store the sliced portion of the target data we are taking the
#target variable from the diabetes dataset and creating a new variable, diabetes_y_train, that contains all target values except the last 30.

diabetes_y_test=diabetes.target[:-30] #[:-30]means take all elements except the last 30
#Here diabetes_y refers to the

#The target variable here is split into training and testing sets

model=linear_model.LinearRegression()#Linear regression model is imported

model.fit(diabetes_x_train,diabetes_y_train)#Here the model is trained using the training sets

diabetes_y_pred=model.predict(diabetes_x_test)#predictions is made using the testing set

print(diabetes_y_pred)

print("weights",model.coef_)
print("intercept",model.intercept_)

print("Mean squared error is:",mean_squared_error(diabetes_y_test,diabetes_y_pred))

plt.scatter(diabetes_x_test,diabetes_y_test)
plt.show()

plt.scatter(diabetes_x_test,diabetes_y_test)
plt.plot(diabetes_x_test,diabetes_y_pred)
plt.show()

"""1.In linear regression model value of a depenedent variable is found by using one or more independent variables

2.Datasets should be gathered for eg if someone wants to predict someones weight based on their height then they would require a dataset containing both height and weight measurements

3.The data has to be split up into training(70%-80%) and testing(20%-30%)

4.A model has to be chosen which will be used to predict

5.The model is trained using the training data,this involves minimalizing the difference between the actual target values and values predicted by the model

6.Once trained predictions can be made

7.Model is evaluated to see how well it performs .Mean squared Error is mostly used which does average of squared errors between predicted and actual values
"""